# Recommened setup as per https://github.com/pyenv/pyenv#basic-github-checkout 2 -> zsh -> homebrew
- name: Permanently add pyenv config to zsh profile
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.zprofile"
    line: eval "$(pyenv init --path)"
    state: present
    create: yes

- name: Permanently add python utilities to path
  ansible.builtin.blockinfile:
    path: "{{ user_home }}/.zshrc"
    block: |
      eval "$(pyenv init -)"
      path=({{ user_home  }}/.local/bin/ $path)
    state: present
    insertafter: ^# User configuration$
    marker: "# {mark} python configuration"
