# Recommened setup as per https://github.com/pyenv/pyenv#basic-github-checkout 2 -> zsh -> homebrew
- name: Permanently add pyenv config to zsh profile
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.zprofile"
    line: eval "$(pyenv init --path)"
    state: present
    create: yes

- name: Permanently add pyenv config to zshrc
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.zshrc"
    line: eval "$(pyenv init -)"
    state: present
    create: yes

- name: Make pip installed packages available on the path
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.zshrc"
    line: path=($HOME/.local/bin/ $path)
    state: present
    create: yes
